#!/bin/sh
VERSION=2.0.7-stanio-3-dev

BASEDIR=$(dirname "$0")
BUILD_SCRIPT="$BASEDIR/stanio-misc/gradlew -p $BASEDIR/stanio-misc -q"
BUILD_DIR=themes/linux

RENDER_ARGS="../../$RENDER_CONFIG \
    --linux-cursors --build-dir $BUILD_DIR \
    --source svg/modern --name Bibata-Modern \
    --source svg/original --name Bibata-Original \
    --source svg/modern-right --name Bibata-Left-Handed-Modern \
    --source svg/original-right --name Bibata-Left-Handed-Original \
    --color Classic,Ice \
    --all-variants --pointer-shadow=9,15,9,0.3 \
    --thin-stroke --stroke-width=6:Hairline \
    --min-stroke-width=0.9 \
    -s /1.25 -r 24,32,40,48,64,72,96"

USER_ARGS=$@ # Why is this necessary?
$BUILD_SCRIPT bibata:run \
	-PbibataJvmArgs="$RENDER_JOPTS -Dbibata.animRateGain=1.25 -Dxcur.cropToContent=true" \
	--args="render $RENDER_ARGS $USER_ARGS" || exit

# Create symlinks and theme files
echo
$BUILD_SCRIPT cleanLinuxThemeFiles linuxThemeFiles \
	-PcursorsVersion=$VERSION -PthemeColors=Classic,Ice || exit
cp -r "$BASEDIR/stanio-misc/bibata/build/linux-themes"/* "$BASEDIR/$BUILD_DIR"
$BUILD_SCRIPT x11Symlinks --args=../../$BUILD_DIR || exit

# Create packages
cd "$BUILD_DIR" || exit
dos2unix --quiet */*.theme
tar cJf ../Bibata-Linux-Classic-v$VERSION.tar.xz             Bibata-[MO]*-Classic*
tar cJf ../Bibata-Linux-Ice-v$VERSION.tar.xz                 Bibata-[MO]*-Ice*
tar cJf ../Bibata-Linux-Left-Handed-Classic-v$VERSION.tar.xz Bibata-Left*-Classic*
tar cJf ../Bibata-Linux-Left-Handed-Ice-v$VERSION.tar.xz     Bibata-Left*-Ice*

echo Done.
