#!/bin/sh
VERSION=2.0.7-stanio-3-dev

BASEDIR=$(dirname "$0")
BUILD_SCRIPT="$BASEDIR/stanio-misc/gradlew -p $BASEDIR/stanio-misc -q"
BUILD_DIR=themes/windows/Bibata-Cursors-v$VERSION

RENDER_ARGS="../../$RENDER_CONFIG \
    --windows-cursors --build-dir $BUILD_DIR \
    --source svg/modern --name Modern \
    --source svg/original --name Original \
    --source svg/modern-right --name Left-Handed-Modern \
    --source svg/original-right --name Left-Handed-Original \
    --color Classic,Ice \
    --all-variants --thin-stroke --pointer-shadow=6,18,6,0.25 \
    -s N,L -r 32,48,64,72,96,128"

USER_ARGS=$@ # Why is this necessary?
$BUILD_SCRIPT bibata:run \
	-PbibataJvmArgs="$RENDER_JOPTS -Dbibata.maxAnimSize=96" \
	--args="render $RENDER_ARGS $USER_ARGS" || exit

# Create setup scripts
echo
$BUILD_SCRIPT cleanWindowsInstallScripts windowsInstallScripts \
	-PcursorsVersion=$VERSION -PwindowsSizes=,Large -PthemeColors=Classic,Ice || exit
cp -r "$BASEDIR/stanio-misc/bibata/build/windows-scripts"/* "$BASEDIR/$BUILD_DIR"

# Create packages
cd "$BUILD_DIR/.." || exit
unix2dos --quiet */*.inf
jar cMf ../Bibata-Windows-Classic-v$VERSION.zip             */[MO]*-Classic* */install-*-Classic.inf
jar cMf ../Bibata-Windows-Ice-v$VERSION.zip                 */[MO]*-Ice*     */install-*-Ice.inf
jar cMf ../Bibata-Windows-Left-Handed-Classic-v$VERSION.zip */Left*-Classic* */install-*-Classic-Left*.inf
jar cMf ../Bibata-Windows-Left-Handed-Ice-v$VERSION.zip     */Left*-Ice*     */install-*-Ice-Left*.inf

echo Done.
