#!/bin/sh
VERSION=2.0.7-stanio-8-dev

BASEDIR=$(dirname "$0")
cd "$BASEDIR"

BUILD_DIR=themes/linux

mousegenRender() {
  export MOUSEGEN_OPTS="-Dmousegen.dynamicOutput=true \
      -Dmousegen.animRateGain=1.333 -Dxcur.cropToContent=true"
  ./mousegen-render \
      --linux-cursors --build-dir "$BUILD_DIR" \
      --source svg/modern --name Bibata-Modern \
      --source svg/original --name Bibata-Original \
      --source svg/modern-right --name Bibata-Left-handed-Modern \
      --source svg/original-right --name Bibata-Left-handed-Original \
      --color Classic,Ice \
      --pointer-shadow=9,15,9,0.3 \
      --thin-stroke --stroke-width=8:Hairline \
      --min-stroke-width=0.9 \
      -s 1.25/1.25 -r 20,24,32,40,48,64,96 "$@"
}

mousegenRender --all-variants "$@"

if [ $# -eq 0 ]; then
  echo
  echo "=== Thinner strokes with expanded fill"
  echo
  . "./expand-fill-remix-linux"
fi

# Create theme files and symlinks
echo
./mousegen linuxThemeFiles "$BUILD_DIR" --config configs/themes.jsonc \
	--var color=Classic --var color=Ice --var version=$VERSION
./mousegen x11Symlinks "$BUILD_DIR"

echo -n "Compressing packages... "
cp configs/COPYING "$BUILD_DIR"
cd "$BUILD_DIR" || exit
dos2unix --quiet COPYING */*.theme
for color in Classic Ice; do
  tar cJf ../Bibata-Linux-$color-v$VERSION.tar.xz             COPYING Bibata-[MO]*-$color*
  tar cJf ../Bibata-Linux-Left-handed-$color-v$VERSION.tar.xz COPYING Bibata-Left*-$color*
done
echo done.
