#!/bin/sh
BASEDIR=$(dirname "$0")

[ -z "$RENDER_JOPTS" ] && RENDER_JOPTS="-Dmousegen.animRateGain=1.333"
echo "Experimental options: $RENDER_JOPTS"
echo

"$BASEDIR/mousegen-tool/gradlew" -p "$BASEDIR/mousegen-tool" \
	-q mousegen:shadowJar -x test --configuration-cache || exit
java $RENDER_JOPTS -Dmousegen.dynamicOutput=true \
	-jar "$BASEDIR/mousegen-tool/mousegen/build/libs/mousegen.jar" \
	render "$@"
