#!/bin/sh
VERSION=2.0.7-stanio-6-dev

BASEDIR=$(dirname "$0")
cd "$BASEDIR"

BUILD_DIR=themes/linux

mousegen() {
  java $MOUSEGEN_JOPTS -jar \
      "mousegen-tool/mousegen/build/libs/mousegen.jar" "$@" || exit
}

mousegenRender() {
  MOUSEGEN_JOPTS="$RENDER_JOPTS -Dmousegen.dynamicOutput=true \
      -Dmousegen.animRateGain=1.333 -Dxcur.cropToContent=true"
  mousegen render "$RENDER_CONFIG" \
      --linux-cursors --build-dir "$BUILD_DIR" \
      --source svg/modern --name Bibata-Modern \
      --source svg/original --name Bibata-Original \
      --source svg/modern-right --name Bibata-Left-handed-Modern \
      --source svg/original-right --name Bibata-Left-handed-Original \
      --color Classic,Ice \
      --pointer-shadow=9,15,9,0.3 \
      --thin-stroke --stroke-width=8:Hairline \
      --min-stroke-width=0.9 \
      -s 1.25/1.25 -r 20,24,32,40,48,64,96 "$@"
  MOUSEGEN_JOPTS=
}

"mousegen-tool/gradlew" -p "mousegen-tool" \
	-q mousegen:shadowJar -x test --configuration-cache || exit
mousegenRender --all-variants "$@"

if [ $# -eq 0 ]; then
  echo
  echo "=== Thinner strokes with expanded fill"
  echo
  . "./expand-fill-remix-linux"
fi

# Create symlinks and theme files
echo
mousegen linuxThemeFiles "$BUILD_DIR" --config configs/themes.jsonc \
	--var color=Classic --var color=Ice --var version=$VERSION
mousegen x11Symlinks "$BUILD_DIR"

# Create packages
echo -n "Compressing packages... "
cp configs/COPYING "$BUILD_DIR"
cd "$BUILD_DIR" || exit
dos2unix --quiet COPYING */*.theme
tar cJf ../Bibata-Linux-Classic-v$VERSION.tar.xz             COPYING Bibata-[MO]*-Classic*
tar cJf ../Bibata-Linux-Ice-v$VERSION.tar.xz                 COPYING Bibata-[MO]*-Ice*
tar cJf ../Bibata-Linux-Left-handed-Classic-v$VERSION.tar.xz COPYING Bibata-Left*-Classic*
tar cJf ../Bibata-Linux-Left-handed-Ice-v$VERSION.tar.xz     COPYING Bibata-Left*-Ice*

echo done.
