#!/bin/sh
VERSION=2.0.7-stanio-7-dev

BASEDIR=$(dirname "$0")
cd "$BASEDIR"

BUILD_DIR=themes/windows/Bibata-Cursors-v$VERSION

mousegenRender() {
  export MOUSEGEN_OPTS="-Dmousegen.dynamicOutput=true \
      -Dmousegen.animRateGain=1.333 -Dmousegen.maxAnimSize=96"
  ./mousegen-render \
      --windows-cursors --build-dir "$BUILD_DIR" \
      --source svg/modern --name Modern \
      --source svg/original --name Original \
      --source svg/modern-right --name Left-handed-Modern \
      --source svg/original-right --name Left-handed-Original \
      --color Classic,Ice \
      --pointer-shadow=9,15,9,0.3 \
      --thin-stroke --stroke-width=8:Hairline \
      --min-stroke-width=0.9 \
      -s N,L -r 32,48,64,72,96,128 "$@"
}

mousegenRender --all-variants "$@"

if [ $# -eq 0 ]; then
  echo
  echo "=== Thinner strokes with expanded fill"
  echo
  . "./expand-fill-remix-windows"
fi

# Create install scripts
echo
./mousegen windowsInstallScripts "$BUILD_DIR" --config configs/themes.jsonc \
	--var color=Classic --var color=Ice --var version=$VERSION \
	--var size=Normal --var size=Large

echo -n "Compressing packages... "
cp configs/COPYING "$BUILD_DIR/.."
cd "$BUILD_DIR/.." || exit
unix2dos --quiet COPYING */*.inf
for color in Classic Ice; do
  jar cMf ../Bibata-Windows-$color-v$VERSION.zip             COPYING */[MO]*-$color* */install-[MO]*-$color*.inf
  jar cMf ../Bibata-Windows-Left-handed-$color-v$VERSION.zip COPYING */Left*-$color* */install-Left*-$color*.inf
done
echo done.
