#!/bin/sh
BASEDIR=$(dirname "$0")
cd "$BASEDIR"

# Download 'mousegen' if it doesn't exist or is outdated
MTAG="0.5"
MTIME=1727340936 # 2024-09-26 11:55:36
if [ ! -f "mousegen" ] || [ $(stat -c "%Y" "mousegen") -lt $MTIME ]; then
  curl --progress-bar --fail -LRo mousegen \
      "https://github.com/stanio/stanio-misc/releases/download/mousegen-$MTAG/mousegen.sh"
  chmod u+x mousegen
fi

[ -z "$MOUSEGEN_OPTS" ] && export \
    MOUSEGEN_OPTS="-Dmousegen.dynamicOutput=true -Dmousegen.animRateGain=1.333"

./mousegen render "$@"
